FROM golang:1.26 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/tasks ./cmd/server

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/tasks /app/tasks
EXPOSE 8082
CMD ["/app/tasks"]
